/*
 * This file is automatically generated and managed by the `omnidoc` package.
 * It is aliased in the tsconfig.json file and can be added to .gitignore or committed. 
 */
import { createCollection } from 'omnidoc/core'

createCollection.setImportMap(
  `mdx:@/content/docs/**/*.{ts,tsx,mdx}`,
  (slug) => import(`../src/content/docs/${slug}.mdx`)
)

export * from 'omnidoc/core'
