/* This file was automatically generated by the `mdxts` package. */
import { createCollection } from 'mdxts/core'

createCollection.setImportMap(
  `mdx:@/content/docs/**/*.{ts,tsx,mdx}`,
  (slug) => import(`@/content/docs/${slug}.mdx`)
)

export * from 'mdxts/core'
